### ISSUE TITLE
Thanks for sharing!

### ISSUE THREAD

**Issue by sesopenko** [mediocregopher/diamond-square#2]
I'd like to thank you for sharing your work because your diagrams in core.clj have helped me gain a grasp of the diamond square algorithm.  I don't work in the same language but the high-level concepts were explained well with the visual schematics under _Coordinate Pattern (The Tricky Part)_.

Thanks again!

**Comment by mediocregopher** [comment]
Well this was a blast from the past :) I'm glad you found the code helpful! Tbh I'd forgotten I'd written it :P
